load("@prelude-nri//node.bzl", "prettier_diffs")

genrule(
    name = "bundle.js",
    out = "bundle.js",
    srcs = glob(["**/*.js"]),
    cmd = "$(exe //:browserify) index.js --outfile $OUT",
    visibility = ["//component-catalog:public"],
)

filegroup(
    name = "src",
    srcs = glob(["**/*.js"]),
    visibility = ["//:node_modules"],
)

prettier_diffs(
    name = "prettier_diffs",
    srcs = glob(["**/*.js"]),
    prettier = "//:prettier",
)
