load("//:browserify.bzl", "browserify")

browserify(
    name = "bundle",
    out = "bundle.js",
    entry = "index.js",
    srcs = glob(["**/*.js"]),
    visibility = ["//component-catalog:public"],
)
