#!/usr/bin/env bash

cd $(git rev-parse --show-toplevel)

if ! test -d buck-out; then
  mkdir buck-out
fi

if ! test -f buck-out/buck2; then
  case "$(uname -s)" in
    Darwin)
      # TODO: adjust for processor type
      curl -L https://github.com/facebook/buck2/releases/download/latest/buck2-aarch64-apple-darwin.zst | zstd -d > buck-out/buck2
      ;;

    Linux)
      curl -L https://github.com/facebook/buck2/releases/download/latest/buck2-x86_64-unknown-linux-gnu.zst | zstd -d > buck-out/buck2
      ;;

    *)
      echo "I don't know how to get a download for $(uname -s)"
      exit 1
      ;;
  esac

  chmod +x buck-out/buck2
fi

exec buck-out/buck2 $@
